// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tQscFEttFW1zeBUCp8w4e2QLhfQUGwQ',
    appId: '1:289564272040:web:2689a52029434358b7e99d',
    messagingSenderId: '289564272040',
    projectId: 'nigerite-94823',
    authDomain: 'nigerite-94823.firebaseapp.com',
    storageBucket: 'nigerite-94823.appspot.com',
    measurementId: 'G-D8YR5BTD61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcixKGW_C9NYHk-Ha8obloMm_e-L8TXbI',
    appId: '1:289564272040:android:859f5837e66998dfb7e99d',
    messagingSenderId: '289564272040',
    projectId: 'nigerite-94823',
    storageBucket: 'nigerite-94823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJPDhgyf0D45fqWnGPLj0XckxxBV2Ewik',
    appId: '1:289564272040:ios:2d43348cf2d8c86db7e99d',
    messagingSenderId: '289564272040',
    projectId: 'nigerite-94823',
    storageBucket: 'nigerite-94823.appspot.com',
    iosClientId: '289564272040-b1qdcgp0g15jsts5ij8bdfmv99ccftis.apps.googleusercontent.com',
    iosBundleId: 'com.example.nigerite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJPDhgyf0D45fqWnGPLj0XckxxBV2Ewik',
    appId: '1:289564272040:ios:07e67c5f46ffdfd6b7e99d',
    messagingSenderId: '289564272040',
    projectId: 'nigerite-94823',
    storageBucket: 'nigerite-94823.appspot.com',
    iosClientId: '289564272040-i0rnj4faqcb1gohpo273eoacau11n28f.apps.googleusercontent.com',
    iosBundleId: 'com.example.nigerite.RunnerTests',
  );
}
